<a href="https://colab.research.google.com/github/pragadishh1/AIML-experiments-230901074/blob/main/Aimlexp12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
df=pd.read_excel("/content/motor_price_dataset_v2.xlsx")
df.head()

   unnamed: 0  Year  Cost
0           0  2000  5434
1           1  2001  5818
2           2  2002  6176
3           3  2003  6437
4           4  2004  6913

In [2]:
df=df.drop("unnamed: 0",axis=1)
df.head()

   Year  Cost
0  2000  5434
1  2001  5818
2  2002  6176
3  2003  6437
4  2004  6913

In [4]:
X=df["Year"]
Y=df["Cost"]
X=np.array(X)
X=X.reshape(-1,1)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X,Y, test_size=0.33, random_state=42)
from sklearn.linear_model import LinearRegression
clf=LinearRegression()
clf.fit(X_train, y_train.values.ravel())

LinearRegression()

In [5]:
y_pred=clf.predict(X_test)
y_pred

array([ 7877.81490385, 10151.44791667,  5604.18189103, 12425.08092949,
        8730.42728365,  8162.01903045,  9298.83553686,  5888.38601763,
       12140.87680288])

In [7]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
print("r2_score",r2_score(y_test,y_pred))

r2_score 0.9962860353183224

In [10]:
new_year=[[2026]]
x=clf.predict(new_year)
x

array([12993.48918269])